version: "3"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_ENV=${APP_ENV}
                - BRAINTREE_MERCHANT_ID=${BRAINTREE_MERCHANT_ID}
                - BRAINTREE_PRIVATE_KEY=${BRAINTREE_PRIVATE_KEY}
                - BRAINTREE_PUBLIC_KEY=${BRAINTREE_PUBLIC_KEY}
                - COOKIE_SECRET=${COOKIE_SECRET}
                - DB_HOST=${DB_HOST}
                - DB_NAME=${DB_NAME}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_PORT=${DB_PORT}
                - DB_SCHEMA=${DB_SCHEMA}
                - DB_USERNAME=${DB_USERNAME}
                - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
                - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
        ports:
            - 3000:3000
        command: ["npm", "run", "start:server"]
        environment:
            APP_ENV: ${APP_ENV}
            BRAINTREE_MERCHANT_ID: ${BRAINTREE_MERCHANT_ID}
            BRAINTREE_PRIVATE_KEY: ${BRAINTREE_PRIVATE_KEY}
            BRAINTREE_PUBLIC_KEY: ${BRAINTREE_PUBLIC_KEY}
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
            SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vendure-server.rule=Host(`g08o44oc8w4ks0ww84k88c88.greatplainsgrowery.com`)"
            - "traefik.http.routers.vendure-server.entrypoints=https"
            - "traefik.http.routers.vendure-server.tls=true"
            - "traefik.http.routers.vendure-server.tls.certresolver=letsencrypt"
            - "traefik.http.services.vendure-server.loadbalancer.server.port=3000"
        networks:
            - vendure-network
        restart: unless-stopped

    worker:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_ENV=${APP_ENV}
                - BRAINTREE_MERCHANT_ID=${BRAINTREE_MERCHANT_ID}
                - BRAINTREE_PRIVATE_KEY=${BRAINTREE_PRIVATE_KEY}
                - BRAINTREE_PUBLIC_KEY=${BRAINTREE_PUBLIC_KEY}
                - COOKIE_SECRET=${COOKIE_SECRET}
                - DB_HOST=${DB_HOST}
                - DB_NAME=${DB_NAME}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_PORT=${DB_PORT}
                - DB_SCHEMA=${DB_SCHEMA}
                - DB_USERNAME=${DB_USERNAME}
                - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
                - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
        command: ["npm", "run", "start:worker"]
        environment:
            APP_ENV: ${APP_ENV}
            BRAINTREE_MERCHANT_ID: ${BRAINTREE_MERCHANT_ID}
            BRAINTREE_PRIVATE_KEY: ${BRAINTREE_PRIVATE_KEY}
            BRAINTREE_PUBLIC_KEY: ${BRAINTREE_PUBLIC_KEY}
            COOKIE_SECRET: ${COOKIE_SECRET}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
            SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vendure-worker.rule=Host(`iggggksc44g4848sggc8gcow.greatplainsgrowery.com`)"
            - "traefik.http.routers.vendure-worker.entrypoints=https"
            - "traefik.http.routers.vendure-worker.tls=true"
            - "traefik.http.routers.vendure-worker.tls.certresolver=letsencrypt"
            - "traefik.http.services.vendure-worker.loadbalancer.server.port=3000"
        networks:
            - vendure-network
        restart: unless-stopped

networks:
    vendure-network:
        driver: bridge